module.exports = Object.freeze({
    STATE_COLORS: {
        SUCCESS: "#27ae60",
        DEFAULT: "#828282",
    },
    USER_TYPE: {
        ADOPTER: "ADOPTER",
        ORGANIZATION: "ORGANIZATION",
    },
    RESIDENCE_TYPE: {
        APARTMENT: "Apartamento",
        HOUSE: "Casa",
        COUNTRY_HOUSE: "Chácara",
        FARM: "Fazenda",
    },
    BRAZILIAN_STATES: {
        AC: "Acre",
        AL: "Alagoas",
        AP: "Amapá",
        AM: "Amazonas",
        BA: "Bahia",
        CE: "Ceará",
        DF: "Distrito Federal",
        ES: "Espírito Santo",
        GO: "Goiás",
        MA: "Maranhão",
        MT: "Mato Grosso",
        MS: "Mato Grosso do Sul",
        MG: "Minas Gerais",
        PA: "Pará",
        PB: "Paraíba",
        PR: "Paraná",
        PE: "Pernambuco",
        PI: "Piauí",
        RJ: "Rio de Janeiro",
        RN: "Rio Grande do Norte",
        RS: "Rio Grande do Sul",
        RO: "Rondônia",
        RR: "Roraima",
        SC: "Santa Catarina",
        SP: "São Paulo",
        SE: "Sergipe",
        TO: "Tocantins",
    },
    ANIMAL_TYPES: {
        DOG: "Cachorro",
        CAT: "Gato",
        RABBIT: "Coelho",
        BIRD: "Pássaro",
        ANY: "Outro",
    },
    ANIMAL_AGE_GROUPS: {
        YOUNG: "Filhote (1 a 12 meses)",
        ADULT: "Adulto (1 a 7 anos)",
        SENIOR: "Sênior (7 anos ou mais)",
    },
    ANIMAL_SIZES: {
        SMALL: "Pequeno",
        MEDIUM: "Médio",
        LARGE: "Grande",
    },
    ANIMAL_COLORS: {
        BLACK: "Preto",
        WHITE: "Branco",
        BROWN: "Marrom",
        MIXED: "Mesclado",
    },
    ROUTINE_TYPES: {
        FULL_TIME: "FULL_TIME",
        FLEXIBLE: "FLEXIBLE",
        AVAILABLE: "AVAILABLE",
    },
    TRAVEL_FREQUENCY: {
        REGULAR: "REGULAR",
        OCCASIONALLY: "OCCASIONALLY",
        RARELLY: "RARELLY",
    },
    DAYS_OF_WEEK: {
        SUNDAY: "Domingo",
        MONDAY: "Segunda-feira",
        TUESDAY: "Terça-feira",
        WEDNESDAY: "Quarta-feira",
        THURSDAY: "Quinta-feira",
        FRIDAY: "Sexta-feira",
        SATURDAY: "Sábado",
    },
});
