version: "3"

services:
  pets-prod:
    image: postgres:latest
    ports:
      - "5434:5432"
    container_name: "pets"
    restart: on-failure
    volumes:
      - pets:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_ROOT_PASSWORD: admin
      POSTGRES_DB: pets

  api-pets:
    container_name: api-pets
    build: ./
    restart: on-failure
    ports:
      - 3335:3335
    depends_on:
      - pets-prod
    env_file:
      - ./.env.prod
    command: sh -c "npm run db && npm start"

volumes:
  pets:
    name: pets
