version: "3"

services:
  pets-dev:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: "pets-dev"
    restart: on-failure
    volumes:
      - petsDev:/var/lib/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_ROOT_PASSWORD: admin
      POSTGRES_DB: pets_dev

  pets-test:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: "pets-test"
    restart: on-failure
    volumes:
      - petsTest:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_ROOT_PASSWORD: admin
      POSTGRES_DB: pets_test

    postgres-test:
        image: postgres:latest
        ports:
            - "5433:5432"
        container_name: "TCC-postgres-test"
        restart: on-failure
        volumes:
            - postgresTestTCC:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_ROOT_PASSWORD: admin
            POSTGRES_DB: tccTest

volumes:
  petsDev:
    name: petsDev
  petsTest:
    name: petsTest
