version: "3"

services:
  pets-prod:
    image: postgres:latest
    ports:
      - "5434:5432"
    container_name: "pets"
    restart: on-failure
    volumes:
      - pets:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api-pets:
    container_name: api-pets
    build: ./
    restart: on-failure
    ports:
      - 3335:3335
    depends_on:
      - pets-prod
    env_file:
      - ./.env
    command: sh -c "npm run db && npm start"

volumes:
  pets:
    name: pets
